export const teamData = [
  {
    title: "Yönetim Kurulu",
    items: [
      {
        name: "Sinancan Öztürk",
        span: "Başkan",
        link: "https://www.linkedin.com/in/sinancan%C3%B6zt%C3%BCrk/",
        image: "/images/team/Sinancan_Ozturk.png",
      },
      {
        name: "Hasan Can Tüfekçi",
        span: "Başkan Yardımcısı",
        link: "https://www.linkedin.com/in/can-t%C3%BCfek%C3%A7i-05121b212/",
        image: "/images/team/Hasan_Can_Tufekci.png",
      },
      {
        name: "Lukas Çakıcı",
        span: "Yazılım Departman Direktörü",
        link: "https://www.linkedin.com/in/lukascakici/",
        image: "/images/team/Lukas_Cakici.png",
      },
      {
        name: "Mehmet Tolga Çakan",
        span: "Yazı İşleri Departman Direktörü",
        link: "https://www.linkedin.com/in/tolga-%C3%A7akan-7aa399204/",
        image: "/images/team/Mehmet_Tolga_Cakan.png",
      },
      {
        name: "Mehmet Akif Duran",
        span: "İnsan Kaynakları Departman Direktörü",
        link: "https://www.linkedin.com/in/mehmet-akif-duran-9a016024a/",
        image: "/images/team/Mehmet_Akif_Duran.png",
      },
      {
        name: "Anılcan Çelikdel",
        span: "Etkinlik Organizasyon Departman Direktörü",
        link: "https://www.linkedin.com/in/anilcancelikdel",
        image: "/images/team/Anilcan_Celikdel.png",
      },
    ],
  },
  {
    title: "Ekip",
    items: [
      {
        name: "Aleyna Suda",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/aleyna-suda-09801a255/",
        image: "/images/team/Aleyna_Suda.png",
      },
      {
        name: "Yeliz Avcı",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/yeliz-avc%C4%B1-898b6a236/",
        image: "/images/team/Yeliz_Avci.png",
      },
      {
        name: "Emirhan Çetinkaya",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/emirhan-c/",
        image: "/images/team/Emirhan_Cetinkaya.png",
      },
      {
        name: "Berfin Algül",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/berfin-algul/",
        image: "/images/team/Berfin_Algul.png",
      },
      {
        name: "Yiğit Kaya Özkan",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/yi%C4%9Fit-kaya-%C3%B6zkan-3b47271b7/",
        image: "/images/team/Yigit_Kaya_Ozkan.png",
      },
      {
        name: "Ege Eyigüngör",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/ege-eyig%C3%BCng%C3%B6r-82b688228/",
        image: "/images/team/Ege_Eyigungor.png",
      },
      {
        name: "Görkem Hasan Güvenç",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/gorkem-guvenc-370534263/",
        image: "/images/team/Gorkem_Hasan_Guvenc.png",
      },
      {
        name: "Muhammet Cem Uçar",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/muhammet-cem-u%C3%A7ar-7b99b4180/",
        image: "/images/team/Muhammet_Cem_Ucar.png",
      },
      {
        name: "Mehmet Yasir Şaher",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/mehmet-yasir-%C5%9Faher/",
        image: "/images/team/Mehmet_Yasir_Saher.png",
      },
      {
        name: "Mehmet Ali Çağlayan",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/mehmet-ali-%C3%A7a%C4%9Flayan-39b632216/",
        image: "/images/team/Mehmet_Ali_Caglayan.png",
      },
      {
        name: "Umut Binöz",
        span: "Medya Departmanı",
        link: "https://www.linkedin.com/in/umut-bin%C3%B6z-b94b8327a",
        image: "/images/team/Umut_Binoz.png",
      },
      {
        name: "Burhan Keten",
        span: "Yazılım Departmanı",
        link: "https://www.linkedin.com/in/ketenburhan/",
        image: "/images/team/Burhan_Keten.png",
      },
      {
        name: "Zafer Şiar Konyar",
        span: "Yazılım Departmanı",
        link: "https://www.linkedin.com/in/zafer-%C5%9Fiar-konyar-7783b01bb/",
        image: "/images/team/Zafer_Siar_Konyar.png",
      },
      {
        name: "Melikşah Altuntaş",
        span: "Yazılım Departmanı",
        link: "https://www.linkedin.com/in/meliksah-altuntas-524093220/",
        image: "/images/team/Meliksah_Altuntas.png",
      },
      {
        name: "Yiğit Şamil Ercedoğan",
        span: "Yazılım Departmanı",
        link: "https://www.linkedin.com/in/yi%C4%9Fit3%C5%9Famil3ercedo%C4%9Fan",
        image: "/images/team/Yigit_Samil_Ercedogan.png",
      },
      {
        name: "Emirhan Sarıdağ",
        span: "Yazılım Departmanı",
        link: "https://www.linkedin.com/in/emirhan-sar%C4%B1da%C4%9F-31a251229/",
        image: "/images/team/Emirhan_Saridag.png",
      },
      {
        name: "Ömer Yiğit",
        span: "Yazılım Departmanı",
        link: "https://www.linkedin.com/in/omer-yigit-99b78a1a3/",
        image: "/images/team/Omer_Yigit.png",
      },
      {
        name: "Dilara Öz",
        span: "İnsan Kaynakları Departmanı",
        link: "https://www.linkedin.com/in/dilara-%C3%B6z-3106a8201/",
        image: "/images/team/Dilara_Oz.png",
      },
      {
        name: "Kağan Kocagöz",
        span: "İnsan Kaynakları Departmanı",
        link: "https://www.linkedin.com/in/samim-ka%C4%9Fan-kocag%C3%B6z-06878327b",
        image: "/images/team/Kagan_Kocagoz.png",
      },
      {
        name: "İbrahim Ethem Delen",
        span: "Yazar",
        link: "https://www.linkedin.com/in/i-ethem-delen-ba653a175/",
        image: "/images/team/Ibrahim_Ethem_Delen.png",
      },
      {
        name: "Ekin Akoğuz",
        span: "Etkinlik Organizasyon Departmanı",
        link: "https://www.linkedin.com/in/ekin-ako%C4%9Fuz-69166423b/",
        image: "/images/team/Ekin_Akoguz.png",
      },
    ],
  },
];
